name: Build, Test & Deploy
on:
  push:
    branches: [master, next]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install
        uses: ./.github/actions/install
      - name: Lint
        run: pnpm lint

  component-tests:
    runs-on: ubuntu-latest
    container:
      image: cypress/browsers:node-20.9.0-chrome-118.0.5993.88-1-ff-118.0.2-edge-118.0.2088.46-1
      options: --user 1001
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install
        uses: ./.github/actions/install
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          component: true
          browser: chrome

  type-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install
        uses: ./.github/actions/install
      - name: Type Check
        run: pnpm type:check

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install
        uses: ./.github/actions/install
      - name: Build project
        run: pnpm build
      - name: Generate types
        run: pnpm type:gen
      - name: Upload Library dist files
        uses: actions/upload-artifact@v4
        with:
          name: gleam-ui
          path: dist

  build-histoire:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install
        uses: ./.github/actions/install
      - name: Build Histoire
        run: pnpm story:build
      - name: Upload Histoire dist files
        uses: actions/upload-artifact@v4
        with:
          name: histoire
          path: .histoire

  publish:
    needs: [lint, component-tests, type-check, build]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install
        uses: ./.github/actions/install
      - name: Download Library dist files
        uses: actions/download-artifact@v4
        with:
          name: gleam-ui
          path: dist
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: pnpm release

  publish-histoire:
    runs-on: ubuntu-latest
    needs: [lint, component-tests, type-check, build, build-histoire]
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: histoire
      - name: Publish to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: d53819673c4e0dc4282dceafde534e5e
          projectName: gleam-ui
          directory: dist
